set(CMAKE_SYSTEM_NAME       Linux)
set(CMAKE_SYSTEM_PROCESSOR  ARM)
set(TOOLCHAIN_PREFIX        armv8-rpi3-linux-gnueabihf-)

# Without that flag CMake is not able to pass test compilation check
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_AR                ${TOOLCHAIN_PREFIX}gcc-ar)
set(CMAKE_ASM_COMPILER      ${TOOLCHAIN_PREFIX}as)
set(CMAKE_C_COMPILER        ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_CXX_COMPILER      ${TOOLCHAIN_PREFIX}g++)
set(CMAKE_OBJCOPY           ${TOOLCHAIN_PREFIX}objcopy CACHE INTERNAL "")
set(CMAKE_RANLIB            ${TOOLCHAIN_PREFIX}gcc-ranlib CACHE INTERNAL "")
set(CMAKE_SIZE_UTIL         ${TOOLCHAIN_PREFIX}size CACHE INTERNAL "")
set(CMAKE_STRIP             ${TOOLCHAIN_PREFIX}strip CACHE INTERNAL "")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
