if (APPLE)
    set(LINUX_ARM_TOOLCHAIN_PATH        "/Volumes/Toolchains/arm-linux-gnueabihf")
    set(BAREMETAL_ARM_TOOLCHAIN_PATH    "/Volumes/Toolchains/gcc-arm-none-eabi-8-2019-q3-update")
elseif (UNIX)
    set(LINUX_ARM_TOOLCHAIN_PATH        "/usr")
    set(BAREMETAL_ARM_TOOLCHAIN_PATH    "/usr")
endif ()

set(FREERTOS_VERSION                    freertos-10.2.1)
set(FREERTOS_PORTABLE                   ARM_CM4F)
