if (APPLE)
    set(LINUX_ARM_TOOLCHAIN_PATH        "/Volumes/Toolchains/arm-linux-gnueabihf")
    set(BAREMETAL_ARM_TOOLCHAIN_PATH    "/Volumes/Toolchains/gcc-arm-none-eabi-9-2019-q4-major")
elseif (UNIX)
    set(LINUX_ARM_TOOLCHAIN_PATH        "/opt/toolchains/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf")
    set(BAREMETAL_ARM_TOOLCHAIN_PATH    "/opt/toolchains/gcc-arm-none-eabi-9-2019-q4-major")
endif ()

set(FREERTOS_VERSION                    freertos-10.2.1)
set(FREERTOS_PORTABLE                   ARM_CM4F)

set(APP_C_FLAGS                         "")
set(APP_CXX_FLAGS                       "")
if (${PLATFORM} STREQUAL baremetal-arm OR ${PLATFORM} STREQUAL freertos-arm)
    set(APP_C_FLAGS                     "-mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb" CACHE INTERNAL "")
    set(APP_CXX_FLAGS                   "-mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb" CACHE INTERNAL "")
endif ()