name: Build FreeRTOS ARM

on: [push, pull_request]

jobs:
  build:
    name: FreeRTOS arm-none-eabi-gcc-${{ matrix.gcc }} ${{ matrix.mode }}
    runs-on: ubuntu-latest
    container:
      image: kubasejdak/arm-none-eabi-gcc:${{ matrix.gcc }}
    strategy:
      matrix:
        gcc: [9]
        mode: [Debug, Release]

    steps:
    - uses: actions/checkout@v1

    - name: Build application
      run: |
        mkdir build
        cd build

        conan install .. --build missing -s build_type=${{ matrix.mode }}
        cmake .. -DPLATFORM=freertos-arm -DCMAKE_BUILD_TYPE=${{ matrix.mode }}
        make
