name: Build FreeRTOS ARM

on: [push, pull_request]

jobs:
  build:
    name: GCC ${{ matrix.mode }}
    runs-on: ubuntu-latest
    container:
      image: kubasejdak/arm-none-eabi-gcc:8
    strategy:
      matrix:
        mode: [Debug, Release]

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build application
      run: |
        mkdir build
        cd build

        cmake .. -DPLATFORM=freertos-arm -DCMAKE_BUILD_TYPE=${{ matrix.mode }}
        make
